import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import Header from '@/components/Header';
import { useEffect, useState } from 'react';
import { useAppDispatch, useAppSelector } from '@/states';
import Quiz from '@/components/Quiz';
import { getUserQuiz, setNewQuiz } from '@/states/Quiz';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [openQuiz, setOpenQuiz] = useState<boolean>(false);
  const quiz = useAppSelector((state) => state.quiz);
  const dispatch = useAppDispatch();
  const handleResume = () => {
    setOpenQuiz(true);
  };
  const addQuizToState = async () => {
    const quiz = getUserQuiz();
    console.log(9898, quiz);
    dispatch(setNewQuiz(quiz));
  };
  useEffect(() => {
    const handleTabClose = (event: any) => {
      event.preventDefault();

      return (event.returnValue = 'Are you sure you want to exit?');
    };

    window.addEventListener('beforeunload', handleTabClose);
    addQuizToState();
    return () => {
      window.removeEventListener('beforeunload', handleTabClose);
    };
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header setOpenQuiz={setOpenQuiz} />

      <div className="flex flex-col justify-center items-center ">
        {quiz !== null && openQuiz === false ? (
          <div
            onClick={handleResume}
            className="bg-blue p-2 hover:opacity-75 rounded-xl hover:cursor-pointer"
          >
            <p className="text-white">Resume Quiz</p>
          </div>
        ) : (
          <>{openQuiz === false && <div>New Quiz</div>}</>
        )}
      </div>
      {openQuiz && <Quiz />}
    </>
  );
}
